deploy:
  branch:
    server: qa.drupal-site.net
    username: test
    dir: '{home}/github/{repo_owner}/{repo_name}/branch/{branch}'
    env_vars:
      docroot: '{home}/domains/{branch}.qa.drupal-site.net'
      domain: '{branch}.qa.drupal-site.net'
      database_name: 'test_{branch}'
      database_user: 'test_{branch}'
      database_pass: 'test_{branch}'
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: '{branch} QA site for {repo_owner}/{repo_name}'
      default_theme: "bootstrap_lite"
      enable_devel: "yes"
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
      remove: '{deploy_dir}/scripts/deploy_remove.sh'
  pull_request:
    server: qa.drupal-site.net
    username: test
    dir: '{home}/github/{repo_owner}/{repo_name}/pr/{pr_number}'
    env_vars:
      docroot: '{home}/domains/{pr_number}.{branch}.qa.drupal-site.net'
      domain: '{pr_number}.{branch}.qa.drupal-site.net'
      database_name: 'test_{branch}_{pr_number}'
      database_user: 'test_{branch}_{pr_number}'
      database_pass: 'test_{branch}_{pr_number}'
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: '{pr_number} {branch} QA site for {repo_owner}/{repo_name}'
      default_theme: "bootstrap_lite"
      enable_devel: "yes"
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
      remove: '{deploy_dir}/scripts/deploy_remove.sh'
test:
  php53:
    branch:
      box: 
        machine: 'dual'
        image: 'analog-subset-130814/leam-php70'
        preemptible: true
      dir: '{home}/github'
      env_vars:
        docroot: '{home}/www'
        domain: 'localhost'
        database_name: 'test'
        database_user: 'test'
        database_pass: ''
        account_user: admin
        account_mail: admin@zen.ci
        account_pass: REPLACE_WITH_ADMIN_PASSWORD
        site_mail: admin@zen.ci
        site_name: test
        tests: '--all'
      scripts:
        init: '{deploy_dir}/scripts/test_deploy_init.sh'
      tests:
        - '{deploy_dir}/scripts/drupal_tests.php'
